# Generated by Django 4.1.dev20211116102130 on 2021-12-16 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='short_data',
            old_name='create_date',
            new_name='creation_date',
        ),
    ]
