# Generated by Django 4.1.dev20211116102130 on 2021-12-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_rename_create_date_short_data_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short_data',
            name='short_url',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
